import 'package:flutter/material.dart';

class profilePage extends StatelessWidget {
  //generated by typing 'stless' ,and write name of this widget in runapp() func
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        backgroundColor: Colors.white,
        body: SafeArea(                                   //avoids getting our content in notches of phone(alt+ent ,rename widget to safe),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              CircleAvatar(
                radius: 50.0,
                backgroundImage:AssetImage('assets/me.jpg'),
              ),
              Text(
                'Jaswant',
                style: TextStyle(
                  fontSize: 40.0,
                  fontFamily: 'Pacifico',
                  color: Color(0xff47455f),
                  fontWeight: FontWeight.bold,
                ),
              ),
              Text(
                'Web Designer',
                style: TextStyle(
                  fontFamily: 'Source Sans Pro',          //done with help of assets
                  fontSize: 20,
                  color:Color(0xff47455f),
                  fontWeight: FontWeight.bold,
                  letterSpacing: 2.5,
                ),
              ),
              SizedBox(height: 20.0,width: 150,
                child: Divider(
                  color:Colors.white,
                ),
              ),
              Card(
                color: Colors.white,
                margin: EdgeInsets.symmetric(vertical: 10.0,horizontal: 25.0),
                child: ListTile(
                  leading: Icon(
                    Icons.email,
                    color: Color(0xff47455f),
                  ),
                  title: Text(
                    'jaswant@gmail.com',
                    style: TextStyle(
                      color: Color(0xff47455f),
                      fontSize: 20.0,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
